# Generated by Django 4.2.4 on 2023-08-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("relecloud", "0004_auto_20210331_2016"),
    ]

    operations = [
        migrations.AddField(
            model_name="cruise",
            name="subtitle",
            field=models.CharField(blank=True, max_length=240, unique=True),
        ),
        migrations.AddField(
            model_name="destination",
            name="subtitle",
            field=models.CharField(blank=True, max_length=240, unique=True),
        ),
    ]
