diff a/.devcontainer/Dockerfile_dev b/.devcontainer/Dockerfile_dev	(rejected hunks)
@@ -1,7 +1,11 @@
-FROM mcr.microsoft.com/devcontainers/python:3.11-bullseye
+FROM mcr.microsoft.com/devcontainers/python:3.12-bullseye
 
 RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
     && apt-get -y install --no-install-recommends postgresql-client \
     && apt-get clean -y && rm -rf /var/lib/apt/lists/*
 
+
+COPY requirements-dev.txt requirements-dev.txt
+COPY src/requirements.txt src/requirements.txt
 RUN python -m pip install --upgrade pip
+RUN python -m pip install -r requirements-dev.txt
\ No newline at end of file
